int32 id
geometry_msgs/Pose position
float32 battery_voltage
float32 battery_percent
int32 floor
int32 node
string map
bool emergency_stop
int32 mission_id
int32 mission_percent
bool idle
bool charging
bool elevator_raised
bool manual
bool automatic
bool pick_done
bool connected
string dispacher_state
bool stick_lights

bool waiting_continue_signal
bool waiting_continue_after_error
bool waiting_continue_after_cancel

bool alarm_or_error_active
string error_msg
