int32 id
geometry_msgs/Pose position
float32 theta
float32 battery
int32 floor
int32 node
string map
bool emergency_stop
int32 mission_id
int32 task_id
bool connected
bool stick_lights

int32 current_task_rlc_id
string current_task_rlc_type

bool waiting_continue_signal
bool alarm_or_error_active

int32 last_task_rlc_ok_id
string last_task_rlc_ok_type

int32 last_task_rlc_error_id
string last_task_rlc_error_type
int32[] zones

string error_msg
