int32 robot
int32 mission
int32[] node_origin
string action_origin
int32[] node_dest
string action_dest
string planner_status
bool error_ack
string msg
---
geometry_msgs/Pose position
int32 current_mission
int32 last_mission
int32 current_node
int32 percent_mission
float32 percent_battery
float32 voltage_battery
bool charging_battery
int32 floor
string dispatcher_state
bool pick_done
bool waiting_continue_signal
bool manual
bool error
bool elevator_raised
bool connected
bool emergency_stop
bool stick_lights
bool ret
string map
string msg
